version: "3.8"

services:
  minecraft:
    image: itzg/minecraft-server:2023.9.1-java17
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      # Type of server from: https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms/
      TYPE: "AUTO_CURSEFORGE"
      # CurseForge developer API key. Escape $ symbols with an additional $
      CF_API_KEY: ""
      CF_PAGE_URL: "https://www.curseforge.com/minecraft/modpacks/all-the-mods-8/files/4504859"
      CF_EXCLUDE_MODS: "486778"
      # Java memory heap size
      MEMORY: "8G"
      # Set this to allow Minecraft to access more RAM for world generation
      # if you keep getting stuck at "Preparing spawn area"
      MAX_MEMORY: "15G"
      VERSION: "1.19.2"
      # Accept the End User License Agreement
      EULA: "TRUE"
      ONLINE_MODE: "FALSE"
      # Allow flight to avoid unexpected server kick
      ALLOW_FLIGHT: "TRUE"
    volumes:
      - /root/mc:/data
    restart: on-failure:3
